name: Build Workflow

run-name: 'Build Workflow -- ${{ github.head_ref || github.ref_name }}'

on:
  push:
  pull_request:

env:
  BRANCH_NAME: ${{github.ref_name}}

jobs:
  build-job:
    name: Build Job
    runs-on: ubuntu-24.04
    if: github.repository_owner == 'ikmdev'
    steps:
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
      - name: Build IKMDEV Code
        uses: ikmdev/maven-clean-install-build-action@main
        with:
          branch_name: ${{env.BRANCH_NAME}}

#      - name: Checkout Repository
#        uses: actions/checkout@v4
#
#      - name: Maven Build
#        if: inputs.branch_name == 'main' || inputs.branch_name == 'master'
#        shell: bash
#        run: |
#          mvn clean install -U \
#            --batch-mode \
#            -e \
#            -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn \
#            -PcodeQuality
#
#      - name: Maven Build -- Feature Branch
#        if: inputs.branch_name != 'main' && inputs.branch_name != 'master'
#        shell: bash
#        run: |
#          mvn clean install -U \
#            --batch-mode \
#            -e \
#            -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn \
#            -Denforcer.skip=true \
#            -PcodeQuality