name: Pipeline Build

run-name: 'Build Pipeline For ${{github.ref_name}}'

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'ikmdev'

    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Build with Maven
        if: github.ref == 'refs/heads/main'
        run: |
          echo 'Running in main branch'
          mvn clean install \

      - name: Build with Maven -- Feature Branch
        if: github.ref != 'refs/heads/main'
        run: |
          echo 'Running in ${{github.ref_name}} branch'
          java --version
          mvn clean install
