name: Sonar Cloud Demo Build Pipeline
     
run-name: 'SonarCloud Demo Build Pipeline For ${{github.ref_name}}'

on:
  workflow_dispatch:

#    push:
#     branches:
#        - "main"
jobs:
  build-job:
    name: Build Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
      - name: Build IKMDEV Code
        uses: ikmdev/maven-clean-install-build-action@main
        with:
          branch_name: ${{env.BRANCH_NAME}}
      - name: SonarCloud Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ 'https://sonarcloud.io/' }}
          SONAR_ORGANIZATION: ${{ 'ikmdev' }}  
          run: mvn verify sonar:sonar 
              -Dsonar.organization=${{ github.repository_owner }}
              -Dsonar.sources=src/main/java 
              -Dsonar.projectKey=${{ github.repository_owner }}_${{ github.event.repository.name }} 
              -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
              -Dsonar.java.binaries=target/classes
              -Dsonar.tests=src/test/java
