name: Code Coverage (Sonar Cloud)

run-name: SonarCloud Scan -- ${{github.ref_name}}

on:
  workflow_dispatch:

#    push:
#     branches:
#        - "main"
jobs:
  code-coverage:
    name: Code Coverage
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
          
      - name: IKMDEV Code Coverage
        uses: ikmdev/maven-code-coverage-action@main
        with:
          branch_name: ${{env.BRANCH_NAME}}
          sonarcloud_token: ${{ secrets.SONAR_TOKEN }}
          sonarcloud_host_url: ${{ 'https://sonarcloud.io/' }}
          sonarcloud_organization: ${{ github.repository_owner }}
          sonarcloud_sources: ${{ 'src/main/java' }}
          sonarcloud_projectKey: ${{ github.repository_owner }}_${{ github.event.repository.name }}
          sonarcloud_coverage_jacoco_xmlReportPaths: ${{ 'target/site/jacoco/jacoco.xml' }}
          sonarcloud_java_binaries: ${{ 'target/classes' }}
          sonarcloud_tests: ${{ 'src/test/java' }}
