on:
  workflow_dispatch:

#    push:
#     branches:
#        - "main"
jobs:
  build-job:
    name: Build Job
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/setup-java@v4
        with:
          sonarcloud_token: ${{ secrets.SONAR_TOKEN }}
          sonar_host_url: ${{ 'https://sonarcloud.io/' }}
          sonar_organization: ${{ github.repository_owner }}
          sonar_sources: src/main/java
          sonar_projectKey: ${{ github.repository_owner }}_${{ github.event.repository.name }}
          sonar_coverage_jacoco_xmlReportPaths: target/site/jacoco/jacoco.xml
          sonar_java_binaries: target/classes
          sonar_tests: src/test/java
          java-version: '21'
          distribution: 'zulu'
      - name: IKMDEV build
        uses: casaras1/maven-clean-install-build-action@main
        with:
          branch_name: ${{env.BRANCH_NAME}}
          
