name: Publish Artifacts Workflow

run-name: 'Publish Artifacts To Nexus -- ${{github.event.workflow_run.head_branch}}'

on:
   workflow_run:
    workflows:
      - Build Workflow
    types:
      - completed
        
        
jobs:
  publish-artifacts:
      name: Publish Artifacts
      runs-on: ubuntu-24.04
      if: github.event.workflow_run.conclusion == 'success' && github.repository_owner == 'ikmdev'
      steps:
      - uses: actions/setup-java@v4
        with:
                java-version: '21'
                distribution: 'zulu'


      - name: Build IKMDEV Code
        uses: ikmdev/maven-clean-install-build-action@test
        with:
          branch_name: ${{env.BRANCH_NAME}}
          sonarcloud_token: ${{ secrets.SONAR_TOKEN }}
          sonarcloud_host_url: ${{ 'https://sonarcloud.io/' }}
          sonarcloud_organization: "ikmdev"
          sonarcloud_projectKey: "ikmdev_${{ github.event.repository.name }}"